title: J. Castanho Correia
email: me@castanhocorreia.com
description: "Castanho Correia. I am a software engineer, specialized in backend development within the Java Virtual Machine (JVM) Ecosystem, mainly using Java and Kotlin languages, and application frameworks such as Spring Boot, Spring MVC and Java/Jakarta EE."
baseurl: ""
url: "https://castanhocorreia.com"
permalink: pretty
exclude:
  - .jekyll-cache
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:year/:month/:day/:slug/
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
