title: J. Castanho Correia
email: me@castanhocorreia.com
description: "J. Castanho Correia is a software engineer with expertise in building scalable and performant web applications. Explore his portfolio and read his blog to learn more about his projects, experiences, and insights."
baseurl: ""
url: "https://castanhocorreia.com"
permalink: pretty
exclude:
  - .jekyll-cache
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:year/:month/:day/:slug/
defaults:
  - scope:
      path: ""
    values:
      http_headers:
        Strict-Transport-Security: "max-age=31536000; includeSubDomains"
sass:
  sass_dir: _sass
  style: :compressed
svg:
  optimize: true
plugins:
  - jekyll-inline-svg
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
