title: J. Castanho Correia
email: me@castanhocorreia.com
description: "Castanho Correia. Software engineer."
baseurl: ""
url: "https://castanhocorreia.com"
permalink: pretty
exclude:
  - .jekyll-cache
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:year/:month/:day/:slug/
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
